// Generated by jextract

package com.hannos.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class pg_query_h extends pg_query_h$shared {

    pg_query_h() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());

    private static final int PG_VERSION_NUM = (int)140006L;
    /**
     * {@snippet lang=c :
     * #define PG_VERSION_NUM 140006
     * }
     */
    public static int PG_VERSION_NUM() {
        return PG_VERSION_NUM;
    }
    /**
     * {@snippet lang=c :
     * typedef long long int64_t
     * }
     */
    public static final OfLong int64_t = pg_query_h.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned long long uint64_t
     * }
     */
    public static final OfLong uint64_t = pg_query_h.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef int64_t int_least64_t
     * }
     */
    public static final OfLong int_least64_t = pg_query_h.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef uint64_t uint_least64_t
     * }
     */
    public static final OfLong uint_least64_t = pg_query_h.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef int64_t int_fast64_t
     * }
     */
    public static final OfLong int_fast64_t = pg_query_h.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef uint64_t uint_fast64_t
     * }
     */
    public static final OfLong uint_fast64_t = pg_query_h.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef int int32_t
     * }
     */
    public static final OfInt int32_t = pg_query_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef unsigned int uint32_t
     * }
     */
    public static final OfInt uint32_t = pg_query_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef int32_t int_least32_t
     * }
     */
    public static final OfInt int_least32_t = pg_query_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef uint32_t uint_least32_t
     * }
     */
    public static final OfInt uint_least32_t = pg_query_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef int32_t int_fast32_t
     * }
     */
    public static final OfInt int_fast32_t = pg_query_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef uint32_t uint_fast32_t
     * }
     */
    public static final OfInt uint_fast32_t = pg_query_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef short int16_t
     * }
     */
    public static final OfShort int16_t = pg_query_h.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef unsigned short uint16_t
     * }
     */
    public static final OfShort uint16_t = pg_query_h.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef int16_t int_least16_t
     * }
     */
    public static final OfShort int_least16_t = pg_query_h.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef uint16_t uint_least16_t
     * }
     */
    public static final OfShort uint_least16_t = pg_query_h.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef int16_t int_fast16_t
     * }
     */
    public static final OfShort int_fast16_t = pg_query_h.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef uint16_t uint_fast16_t
     * }
     */
    public static final OfShort uint_fast16_t = pg_query_h.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef signed char int8_t
     * }
     */
    public static final OfByte int8_t = pg_query_h.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef unsigned char uint8_t
     * }
     */
    public static final OfByte uint8_t = pg_query_h.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef int8_t int_least8_t
     * }
     */
    public static final OfByte int_least8_t = pg_query_h.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef uint8_t uint_least8_t
     * }
     */
    public static final OfByte uint_least8_t = pg_query_h.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef int8_t int_fast8_t
     * }
     */
    public static final OfByte int_fast8_t = pg_query_h.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef uint8_t uint_fast8_t
     * }
     */
    public static final OfByte uint_fast8_t = pg_query_h.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef long long intptr_t
     * }
     */
    public static final OfLong intptr_t = pg_query_h.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned long long uintptr_t
     * }
     */
    public static final OfLong uintptr_t = pg_query_h.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef long long intmax_t
     * }
     */
    public static final OfLong intmax_t = pg_query_h.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned long long uintmax_t
     * }
     */
    public static final OfLong uintmax_t = pg_query_h.C_LONG_LONG;

    private static class pg_query_normalize {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            PgQueryNormalizeResult.layout(),
            pg_query_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("pg_query_normalize");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * PgQueryNormalizeResult pg_query_normalize(const char *input)
     * }
     */
    public static FunctionDescriptor pg_query_normalize$descriptor() {
        return pg_query_normalize.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * PgQueryNormalizeResult pg_query_normalize(const char *input)
     * }
     */
    public static MethodHandle pg_query_normalize$handle() {
        return pg_query_normalize.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * PgQueryNormalizeResult pg_query_normalize(const char *input)
     * }
     */
    public static MemorySegment pg_query_normalize$address() {
        return pg_query_normalize.ADDR;
    }

    /**
     * {@snippet lang=c :
     * PgQueryNormalizeResult pg_query_normalize(const char *input)
     * }
     */
    public static MemorySegment pg_query_normalize(SegmentAllocator allocator, MemorySegment input) {
        var mh$ = pg_query_normalize.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("pg_query_normalize", allocator, input);
            }
            return (MemorySegment)mh$.invokeExact(allocator, input);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class pg_query_scan {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            PgQueryScanResult.layout(),
            pg_query_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("pg_query_scan");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * PgQueryScanResult pg_query_scan(const char *input)
     * }
     */
    public static FunctionDescriptor pg_query_scan$descriptor() {
        return pg_query_scan.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * PgQueryScanResult pg_query_scan(const char *input)
     * }
     */
    public static MethodHandle pg_query_scan$handle() {
        return pg_query_scan.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * PgQueryScanResult pg_query_scan(const char *input)
     * }
     */
    public static MemorySegment pg_query_scan$address() {
        return pg_query_scan.ADDR;
    }

    /**
     * {@snippet lang=c :
     * PgQueryScanResult pg_query_scan(const char *input)
     * }
     */
    public static MemorySegment pg_query_scan(SegmentAllocator allocator, MemorySegment input) {
        var mh$ = pg_query_scan.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("pg_query_scan", allocator, input);
            }
            return (MemorySegment)mh$.invokeExact(allocator, input);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class pg_query_parse {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            PgQueryParseResult.layout(),
            pg_query_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("pg_query_parse");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * PgQueryParseResult pg_query_parse(const char *input)
     * }
     */
    public static FunctionDescriptor pg_query_parse$descriptor() {
        return pg_query_parse.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * PgQueryParseResult pg_query_parse(const char *input)
     * }
     */
    public static MethodHandle pg_query_parse$handle() {
        return pg_query_parse.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * PgQueryParseResult pg_query_parse(const char *input)
     * }
     */
    public static MemorySegment pg_query_parse$address() {
        return pg_query_parse.ADDR;
    }

    /**
     * {@snippet lang=c :
     * PgQueryParseResult pg_query_parse(const char *input)
     * }
     */
    public static MemorySegment pg_query_parse(SegmentAllocator allocator, MemorySegment input) {
        var mh$ = pg_query_parse.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("pg_query_parse", allocator, input);
            }
            return (MemorySegment)mh$.invokeExact(allocator, input);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class pg_query_parse_protobuf {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            PgQueryProtobufParseResult.layout(),
            pg_query_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("pg_query_parse_protobuf");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * PgQueryProtobufParseResult pg_query_parse_protobuf(const char *input)
     * }
     */
    public static FunctionDescriptor pg_query_parse_protobuf$descriptor() {
        return pg_query_parse_protobuf.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * PgQueryProtobufParseResult pg_query_parse_protobuf(const char *input)
     * }
     */
    public static MethodHandle pg_query_parse_protobuf$handle() {
        return pg_query_parse_protobuf.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * PgQueryProtobufParseResult pg_query_parse_protobuf(const char *input)
     * }
     */
    public static MemorySegment pg_query_parse_protobuf$address() {
        return pg_query_parse_protobuf.ADDR;
    }

    /**
     * {@snippet lang=c :
     * PgQueryProtobufParseResult pg_query_parse_protobuf(const char *input)
     * }
     */
    public static MemorySegment pg_query_parse_protobuf(SegmentAllocator allocator, MemorySegment input) {
        var mh$ = pg_query_parse_protobuf.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("pg_query_parse_protobuf", allocator, input);
            }
            return (MemorySegment)mh$.invokeExact(allocator, input);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class pg_query_parse_plpgsql {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            PgQueryPlpgsqlParseResult.layout(),
            pg_query_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("pg_query_parse_plpgsql");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * PgQueryPlpgsqlParseResult pg_query_parse_plpgsql(const char *input)
     * }
     */
    public static FunctionDescriptor pg_query_parse_plpgsql$descriptor() {
        return pg_query_parse_plpgsql.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * PgQueryPlpgsqlParseResult pg_query_parse_plpgsql(const char *input)
     * }
     */
    public static MethodHandle pg_query_parse_plpgsql$handle() {
        return pg_query_parse_plpgsql.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * PgQueryPlpgsqlParseResult pg_query_parse_plpgsql(const char *input)
     * }
     */
    public static MemorySegment pg_query_parse_plpgsql$address() {
        return pg_query_parse_plpgsql.ADDR;
    }

    /**
     * {@snippet lang=c :
     * PgQueryPlpgsqlParseResult pg_query_parse_plpgsql(const char *input)
     * }
     */
    public static MemorySegment pg_query_parse_plpgsql(SegmentAllocator allocator, MemorySegment input) {
        var mh$ = pg_query_parse_plpgsql.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("pg_query_parse_plpgsql", allocator, input);
            }
            return (MemorySegment)mh$.invokeExact(allocator, input);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class pg_query_fingerprint {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            PgQueryFingerprintResult.layout(),
            pg_query_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("pg_query_fingerprint");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * PgQueryFingerprintResult pg_query_fingerprint(const char *input)
     * }
     */
    public static FunctionDescriptor pg_query_fingerprint$descriptor() {
        return pg_query_fingerprint.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * PgQueryFingerprintResult pg_query_fingerprint(const char *input)
     * }
     */
    public static MethodHandle pg_query_fingerprint$handle() {
        return pg_query_fingerprint.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * PgQueryFingerprintResult pg_query_fingerprint(const char *input)
     * }
     */
    public static MemorySegment pg_query_fingerprint$address() {
        return pg_query_fingerprint.ADDR;
    }

    /**
     * {@snippet lang=c :
     * PgQueryFingerprintResult pg_query_fingerprint(const char *input)
     * }
     */
    public static MemorySegment pg_query_fingerprint(SegmentAllocator allocator, MemorySegment input) {
        var mh$ = pg_query_fingerprint.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("pg_query_fingerprint", allocator, input);
            }
            return (MemorySegment)mh$.invokeExact(allocator, input);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class pg_query_split_with_scanner {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            PgQuerySplitResult.layout(),
            pg_query_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("pg_query_split_with_scanner");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * PgQuerySplitResult pg_query_split_with_scanner(const char *input)
     * }
     */
    public static FunctionDescriptor pg_query_split_with_scanner$descriptor() {
        return pg_query_split_with_scanner.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * PgQuerySplitResult pg_query_split_with_scanner(const char *input)
     * }
     */
    public static MethodHandle pg_query_split_with_scanner$handle() {
        return pg_query_split_with_scanner.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * PgQuerySplitResult pg_query_split_with_scanner(const char *input)
     * }
     */
    public static MemorySegment pg_query_split_with_scanner$address() {
        return pg_query_split_with_scanner.ADDR;
    }

    /**
     * {@snippet lang=c :
     * PgQuerySplitResult pg_query_split_with_scanner(const char *input)
     * }
     */
    public static MemorySegment pg_query_split_with_scanner(SegmentAllocator allocator, MemorySegment input) {
        var mh$ = pg_query_split_with_scanner.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("pg_query_split_with_scanner", allocator, input);
            }
            return (MemorySegment)mh$.invokeExact(allocator, input);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class pg_query_split_with_parser {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            PgQuerySplitResult.layout(),
            pg_query_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("pg_query_split_with_parser");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * PgQuerySplitResult pg_query_split_with_parser(const char *input)
     * }
     */
    public static FunctionDescriptor pg_query_split_with_parser$descriptor() {
        return pg_query_split_with_parser.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * PgQuerySplitResult pg_query_split_with_parser(const char *input)
     * }
     */
    public static MethodHandle pg_query_split_with_parser$handle() {
        return pg_query_split_with_parser.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * PgQuerySplitResult pg_query_split_with_parser(const char *input)
     * }
     */
    public static MemorySegment pg_query_split_with_parser$address() {
        return pg_query_split_with_parser.ADDR;
    }

    /**
     * {@snippet lang=c :
     * PgQuerySplitResult pg_query_split_with_parser(const char *input)
     * }
     */
    public static MemorySegment pg_query_split_with_parser(SegmentAllocator allocator, MemorySegment input) {
        var mh$ = pg_query_split_with_parser.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("pg_query_split_with_parser", allocator, input);
            }
            return (MemorySegment)mh$.invokeExact(allocator, input);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class pg_query_deparse_protobuf {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            PgQueryDeparseResult.layout(),
            PgQueryProtobuf.layout()
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("pg_query_deparse_protobuf");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * PgQueryDeparseResult pg_query_deparse_protobuf(PgQueryProtobuf parse_tree)
     * }
     */
    public static FunctionDescriptor pg_query_deparse_protobuf$descriptor() {
        return pg_query_deparse_protobuf.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * PgQueryDeparseResult pg_query_deparse_protobuf(PgQueryProtobuf parse_tree)
     * }
     */
    public static MethodHandle pg_query_deparse_protobuf$handle() {
        return pg_query_deparse_protobuf.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * PgQueryDeparseResult pg_query_deparse_protobuf(PgQueryProtobuf parse_tree)
     * }
     */
    public static MemorySegment pg_query_deparse_protobuf$address() {
        return pg_query_deparse_protobuf.ADDR;
    }

    /**
     * {@snippet lang=c :
     * PgQueryDeparseResult pg_query_deparse_protobuf(PgQueryProtobuf parse_tree)
     * }
     */
    public static MemorySegment pg_query_deparse_protobuf(SegmentAllocator allocator, MemorySegment parse_tree) {
        var mh$ = pg_query_deparse_protobuf.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("pg_query_deparse_protobuf", allocator, parse_tree);
            }
            return (MemorySegment)mh$.invokeExact(allocator, parse_tree);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class pg_query_free_normalize_result {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            PgQueryNormalizeResult.layout()
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("pg_query_free_normalize_result");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void pg_query_free_normalize_result(PgQueryNormalizeResult result)
     * }
     */
    public static FunctionDescriptor pg_query_free_normalize_result$descriptor() {
        return pg_query_free_normalize_result.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void pg_query_free_normalize_result(PgQueryNormalizeResult result)
     * }
     */
    public static MethodHandle pg_query_free_normalize_result$handle() {
        return pg_query_free_normalize_result.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void pg_query_free_normalize_result(PgQueryNormalizeResult result)
     * }
     */
    public static MemorySegment pg_query_free_normalize_result$address() {
        return pg_query_free_normalize_result.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void pg_query_free_normalize_result(PgQueryNormalizeResult result)
     * }
     */
    public static void pg_query_free_normalize_result(MemorySegment result) {
        var mh$ = pg_query_free_normalize_result.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("pg_query_free_normalize_result", result);
            }
            mh$.invokeExact(result);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class pg_query_free_scan_result {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            PgQueryScanResult.layout()
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("pg_query_free_scan_result");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void pg_query_free_scan_result(PgQueryScanResult result)
     * }
     */
    public static FunctionDescriptor pg_query_free_scan_result$descriptor() {
        return pg_query_free_scan_result.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void pg_query_free_scan_result(PgQueryScanResult result)
     * }
     */
    public static MethodHandle pg_query_free_scan_result$handle() {
        return pg_query_free_scan_result.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void pg_query_free_scan_result(PgQueryScanResult result)
     * }
     */
    public static MemorySegment pg_query_free_scan_result$address() {
        return pg_query_free_scan_result.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void pg_query_free_scan_result(PgQueryScanResult result)
     * }
     */
    public static void pg_query_free_scan_result(MemorySegment result) {
        var mh$ = pg_query_free_scan_result.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("pg_query_free_scan_result", result);
            }
            mh$.invokeExact(result);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class pg_query_free_parse_result {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            PgQueryParseResult.layout()
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("pg_query_free_parse_result");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void pg_query_free_parse_result(PgQueryParseResult result)
     * }
     */
    public static FunctionDescriptor pg_query_free_parse_result$descriptor() {
        return pg_query_free_parse_result.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void pg_query_free_parse_result(PgQueryParseResult result)
     * }
     */
    public static MethodHandle pg_query_free_parse_result$handle() {
        return pg_query_free_parse_result.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void pg_query_free_parse_result(PgQueryParseResult result)
     * }
     */
    public static MemorySegment pg_query_free_parse_result$address() {
        return pg_query_free_parse_result.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void pg_query_free_parse_result(PgQueryParseResult result)
     * }
     */
    public static void pg_query_free_parse_result(MemorySegment result) {
        var mh$ = pg_query_free_parse_result.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("pg_query_free_parse_result", result);
            }
            mh$.invokeExact(result);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class pg_query_free_split_result {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            PgQuerySplitResult.layout()
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("pg_query_free_split_result");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void pg_query_free_split_result(PgQuerySplitResult result)
     * }
     */
    public static FunctionDescriptor pg_query_free_split_result$descriptor() {
        return pg_query_free_split_result.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void pg_query_free_split_result(PgQuerySplitResult result)
     * }
     */
    public static MethodHandle pg_query_free_split_result$handle() {
        return pg_query_free_split_result.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void pg_query_free_split_result(PgQuerySplitResult result)
     * }
     */
    public static MemorySegment pg_query_free_split_result$address() {
        return pg_query_free_split_result.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void pg_query_free_split_result(PgQuerySplitResult result)
     * }
     */
    public static void pg_query_free_split_result(MemorySegment result) {
        var mh$ = pg_query_free_split_result.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("pg_query_free_split_result", result);
            }
            mh$.invokeExact(result);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class pg_query_free_deparse_result {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            PgQueryDeparseResult.layout()
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("pg_query_free_deparse_result");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void pg_query_free_deparse_result(PgQueryDeparseResult result)
     * }
     */
    public static FunctionDescriptor pg_query_free_deparse_result$descriptor() {
        return pg_query_free_deparse_result.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void pg_query_free_deparse_result(PgQueryDeparseResult result)
     * }
     */
    public static MethodHandle pg_query_free_deparse_result$handle() {
        return pg_query_free_deparse_result.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void pg_query_free_deparse_result(PgQueryDeparseResult result)
     * }
     */
    public static MemorySegment pg_query_free_deparse_result$address() {
        return pg_query_free_deparse_result.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void pg_query_free_deparse_result(PgQueryDeparseResult result)
     * }
     */
    public static void pg_query_free_deparse_result(MemorySegment result) {
        var mh$ = pg_query_free_deparse_result.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("pg_query_free_deparse_result", result);
            }
            mh$.invokeExact(result);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class pg_query_free_protobuf_parse_result {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            PgQueryProtobufParseResult.layout()
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("pg_query_free_protobuf_parse_result");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void pg_query_free_protobuf_parse_result(PgQueryProtobufParseResult result)
     * }
     */
    public static FunctionDescriptor pg_query_free_protobuf_parse_result$descriptor() {
        return pg_query_free_protobuf_parse_result.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void pg_query_free_protobuf_parse_result(PgQueryProtobufParseResult result)
     * }
     */
    public static MethodHandle pg_query_free_protobuf_parse_result$handle() {
        return pg_query_free_protobuf_parse_result.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void pg_query_free_protobuf_parse_result(PgQueryProtobufParseResult result)
     * }
     */
    public static MemorySegment pg_query_free_protobuf_parse_result$address() {
        return pg_query_free_protobuf_parse_result.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void pg_query_free_protobuf_parse_result(PgQueryProtobufParseResult result)
     * }
     */
    public static void pg_query_free_protobuf_parse_result(MemorySegment result) {
        var mh$ = pg_query_free_protobuf_parse_result.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("pg_query_free_protobuf_parse_result", result);
            }
            mh$.invokeExact(result);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class pg_query_free_plpgsql_parse_result {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            PgQueryPlpgsqlParseResult.layout()
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("pg_query_free_plpgsql_parse_result");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void pg_query_free_plpgsql_parse_result(PgQueryPlpgsqlParseResult result)
     * }
     */
    public static FunctionDescriptor pg_query_free_plpgsql_parse_result$descriptor() {
        return pg_query_free_plpgsql_parse_result.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void pg_query_free_plpgsql_parse_result(PgQueryPlpgsqlParseResult result)
     * }
     */
    public static MethodHandle pg_query_free_plpgsql_parse_result$handle() {
        return pg_query_free_plpgsql_parse_result.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void pg_query_free_plpgsql_parse_result(PgQueryPlpgsqlParseResult result)
     * }
     */
    public static MemorySegment pg_query_free_plpgsql_parse_result$address() {
        return pg_query_free_plpgsql_parse_result.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void pg_query_free_plpgsql_parse_result(PgQueryPlpgsqlParseResult result)
     * }
     */
    public static void pg_query_free_plpgsql_parse_result(MemorySegment result) {
        var mh$ = pg_query_free_plpgsql_parse_result.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("pg_query_free_plpgsql_parse_result", result);
            }
            mh$.invokeExact(result);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class pg_query_free_fingerprint_result {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            PgQueryFingerprintResult.layout()
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("pg_query_free_fingerprint_result");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void pg_query_free_fingerprint_result(PgQueryFingerprintResult result)
     * }
     */
    public static FunctionDescriptor pg_query_free_fingerprint_result$descriptor() {
        return pg_query_free_fingerprint_result.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void pg_query_free_fingerprint_result(PgQueryFingerprintResult result)
     * }
     */
    public static MethodHandle pg_query_free_fingerprint_result$handle() {
        return pg_query_free_fingerprint_result.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void pg_query_free_fingerprint_result(PgQueryFingerprintResult result)
     * }
     */
    public static MemorySegment pg_query_free_fingerprint_result$address() {
        return pg_query_free_fingerprint_result.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void pg_query_free_fingerprint_result(PgQueryFingerprintResult result)
     * }
     */
    public static void pg_query_free_fingerprint_result(MemorySegment result) {
        var mh$ = pg_query_free_fingerprint_result.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("pg_query_free_fingerprint_result", result);
            }
            mh$.invokeExact(result);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class pg_query_exit {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("pg_query_exit");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void pg_query_exit()
     * }
     */
    public static FunctionDescriptor pg_query_exit$descriptor() {
        return pg_query_exit.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void pg_query_exit()
     * }
     */
    public static MethodHandle pg_query_exit$handle() {
        return pg_query_exit.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void pg_query_exit()
     * }
     */
    public static MemorySegment pg_query_exit$address() {
        return pg_query_exit.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void pg_query_exit()
     * }
     */
    public static void pg_query_exit() {
        var mh$ = pg_query_exit.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("pg_query_exit");
            }
            mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class pg_query_init {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("pg_query_init");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void pg_query_init()
     * }
     */
    public static FunctionDescriptor pg_query_init$descriptor() {
        return pg_query_init.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void pg_query_init()
     * }
     */
    public static MethodHandle pg_query_init$handle() {
        return pg_query_init.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void pg_query_init()
     * }
     */
    public static MemorySegment pg_query_init$address() {
        return pg_query_init.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void pg_query_init()
     * }
     */
    public static void pg_query_init() {
        var mh$ = pg_query_init.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("pg_query_init");
            }
            mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
    private static final long INT64_MAX = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define INT64_MAX 9223372036854775807
     * }
     */
    public static long INT64_MAX() {
        return INT64_MAX;
    }
    private static final long INT64_MIN = -9223372036854775808L;
    /**
     * {@snippet lang=c :
     * #define INT64_MIN -9223372036854775808
     * }
     */
    public static long INT64_MIN() {
        return INT64_MIN;
    }
    private static final long UINT64_MAX = -1L;
    /**
     * {@snippet lang=c :
     * #define UINT64_MAX -1
     * }
     */
    public static long UINT64_MAX() {
        return UINT64_MAX;
    }
    private static final long __INT_LEAST64_MIN = -9223372036854775808L;
    /**
     * {@snippet lang=c :
     * #define __INT_LEAST64_MIN -9223372036854775808
     * }
     */
    public static long __INT_LEAST64_MIN() {
        return __INT_LEAST64_MIN;
    }
    private static final long __INT_LEAST64_MAX = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define __INT_LEAST64_MAX 9223372036854775807
     * }
     */
    public static long __INT_LEAST64_MAX() {
        return __INT_LEAST64_MAX;
    }
    private static final long __UINT_LEAST64_MAX = -1L;
    /**
     * {@snippet lang=c :
     * #define __UINT_LEAST64_MAX -1
     * }
     */
    public static long __UINT_LEAST64_MAX() {
        return __UINT_LEAST64_MAX;
    }
    private static final int __INT_LEAST32_MIN = (int)-2147483648L;
    /**
     * {@snippet lang=c :
     * #define __INT_LEAST32_MIN -2147483648
     * }
     */
    public static int __INT_LEAST32_MIN() {
        return __INT_LEAST32_MIN;
    }
    private static final int __INT_LEAST32_MAX = (int)2147483647L;
    /**
     * {@snippet lang=c :
     * #define __INT_LEAST32_MAX 2147483647
     * }
     */
    public static int __INT_LEAST32_MAX() {
        return __INT_LEAST32_MAX;
    }
    private static final int __UINT_LEAST32_MAX = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define __UINT_LEAST32_MAX 4294967295
     * }
     */
    public static int __UINT_LEAST32_MAX() {
        return __UINT_LEAST32_MAX;
    }
    private static final int __INT_LEAST16_MIN = (int)-32768L;
    /**
     * {@snippet lang=c :
     * #define __INT_LEAST16_MIN -32768
     * }
     */
    public static int __INT_LEAST16_MIN() {
        return __INT_LEAST16_MIN;
    }
    private static final int __INT_LEAST16_MAX = (int)32767L;
    /**
     * {@snippet lang=c :
     * #define __INT_LEAST16_MAX 32767
     * }
     */
    public static int __INT_LEAST16_MAX() {
        return __INT_LEAST16_MAX;
    }
    private static final int __UINT_LEAST16_MAX = (int)65535L;
    /**
     * {@snippet lang=c :
     * #define __UINT_LEAST16_MAX 65535
     * }
     */
    public static int __UINT_LEAST16_MAX() {
        return __UINT_LEAST16_MAX;
    }
    private static final int __INT_LEAST8_MIN = (int)-128L;
    /**
     * {@snippet lang=c :
     * #define __INT_LEAST8_MIN -128
     * }
     */
    public static int __INT_LEAST8_MIN() {
        return __INT_LEAST8_MIN;
    }
    private static final int __INT_LEAST8_MAX = (int)127L;
    /**
     * {@snippet lang=c :
     * #define __INT_LEAST8_MAX 127
     * }
     */
    public static int __INT_LEAST8_MAX() {
        return __INT_LEAST8_MAX;
    }
    private static final int __UINT_LEAST8_MAX = (int)255L;
    /**
     * {@snippet lang=c :
     * #define __UINT_LEAST8_MAX 255
     * }
     */
    public static int __UINT_LEAST8_MAX() {
        return __UINT_LEAST8_MAX;
    }
    private static final long INT_LEAST64_MIN = -9223372036854775808L;
    /**
     * {@snippet lang=c :
     * #define INT_LEAST64_MIN -9223372036854775808
     * }
     */
    public static long INT_LEAST64_MIN() {
        return INT_LEAST64_MIN;
    }
    private static final long INT_LEAST64_MAX = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define INT_LEAST64_MAX 9223372036854775807
     * }
     */
    public static long INT_LEAST64_MAX() {
        return INT_LEAST64_MAX;
    }
    private static final long UINT_LEAST64_MAX = -1L;
    /**
     * {@snippet lang=c :
     * #define UINT_LEAST64_MAX -1
     * }
     */
    public static long UINT_LEAST64_MAX() {
        return UINT_LEAST64_MAX;
    }
    private static final long INT_FAST64_MIN = -9223372036854775808L;
    /**
     * {@snippet lang=c :
     * #define INT_FAST64_MIN -9223372036854775808
     * }
     */
    public static long INT_FAST64_MIN() {
        return INT_FAST64_MIN;
    }
    private static final long INT_FAST64_MAX = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define INT_FAST64_MAX 9223372036854775807
     * }
     */
    public static long INT_FAST64_MAX() {
        return INT_FAST64_MAX;
    }
    private static final long UINT_FAST64_MAX = -1L;
    /**
     * {@snippet lang=c :
     * #define UINT_FAST64_MAX -1
     * }
     */
    public static long UINT_FAST64_MAX() {
        return UINT_FAST64_MAX;
    }
    private static final int INT32_MAX = (int)2147483647L;
    /**
     * {@snippet lang=c :
     * #define INT32_MAX 2147483647
     * }
     */
    public static int INT32_MAX() {
        return INT32_MAX;
    }
    private static final int INT32_MIN = (int)-2147483648L;
    /**
     * {@snippet lang=c :
     * #define INT32_MIN -2147483648
     * }
     */
    public static int INT32_MIN() {
        return INT32_MIN;
    }
    private static final int UINT32_MAX = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define UINT32_MAX 4294967295
     * }
     */
    public static int UINT32_MAX() {
        return UINT32_MAX;
    }
    private static final int INT_LEAST32_MIN = (int)-2147483648L;
    /**
     * {@snippet lang=c :
     * #define INT_LEAST32_MIN -2147483648
     * }
     */
    public static int INT_LEAST32_MIN() {
        return INT_LEAST32_MIN;
    }
    private static final int INT_LEAST32_MAX = (int)2147483647L;
    /**
     * {@snippet lang=c :
     * #define INT_LEAST32_MAX 2147483647
     * }
     */
    public static int INT_LEAST32_MAX() {
        return INT_LEAST32_MAX;
    }
    private static final int UINT_LEAST32_MAX = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define UINT_LEAST32_MAX 4294967295
     * }
     */
    public static int UINT_LEAST32_MAX() {
        return UINT_LEAST32_MAX;
    }
    private static final int INT_FAST32_MIN = (int)-2147483648L;
    /**
     * {@snippet lang=c :
     * #define INT_FAST32_MIN -2147483648
     * }
     */
    public static int INT_FAST32_MIN() {
        return INT_FAST32_MIN;
    }
    private static final int INT_FAST32_MAX = (int)2147483647L;
    /**
     * {@snippet lang=c :
     * #define INT_FAST32_MAX 2147483647
     * }
     */
    public static int INT_FAST32_MAX() {
        return INT_FAST32_MAX;
    }
    private static final int UINT_FAST32_MAX = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define UINT_FAST32_MAX 4294967295
     * }
     */
    public static int UINT_FAST32_MAX() {
        return UINT_FAST32_MAX;
    }
    private static final int INT16_MAX = (int)32767L;
    /**
     * {@snippet lang=c :
     * #define INT16_MAX 32767
     * }
     */
    public static int INT16_MAX() {
        return INT16_MAX;
    }
    private static final int INT16_MIN = (int)-32768L;
    /**
     * {@snippet lang=c :
     * #define INT16_MIN -32768
     * }
     */
    public static int INT16_MIN() {
        return INT16_MIN;
    }
    private static final int UINT16_MAX = (int)65535L;
    /**
     * {@snippet lang=c :
     * #define UINT16_MAX 65535
     * }
     */
    public static int UINT16_MAX() {
        return UINT16_MAX;
    }
    private static final int INT_LEAST16_MIN = (int)-32768L;
    /**
     * {@snippet lang=c :
     * #define INT_LEAST16_MIN -32768
     * }
     */
    public static int INT_LEAST16_MIN() {
        return INT_LEAST16_MIN;
    }
    private static final int INT_LEAST16_MAX = (int)32767L;
    /**
     * {@snippet lang=c :
     * #define INT_LEAST16_MAX 32767
     * }
     */
    public static int INT_LEAST16_MAX() {
        return INT_LEAST16_MAX;
    }
    private static final int UINT_LEAST16_MAX = (int)65535L;
    /**
     * {@snippet lang=c :
     * #define UINT_LEAST16_MAX 65535
     * }
     */
    public static int UINT_LEAST16_MAX() {
        return UINT_LEAST16_MAX;
    }
    private static final int INT_FAST16_MIN = (int)-32768L;
    /**
     * {@snippet lang=c :
     * #define INT_FAST16_MIN -32768
     * }
     */
    public static int INT_FAST16_MIN() {
        return INT_FAST16_MIN;
    }
    private static final int INT_FAST16_MAX = (int)32767L;
    /**
     * {@snippet lang=c :
     * #define INT_FAST16_MAX 32767
     * }
     */
    public static int INT_FAST16_MAX() {
        return INT_FAST16_MAX;
    }
    private static final int UINT_FAST16_MAX = (int)65535L;
    /**
     * {@snippet lang=c :
     * #define UINT_FAST16_MAX 65535
     * }
     */
    public static int UINT_FAST16_MAX() {
        return UINT_FAST16_MAX;
    }
    private static final int INT8_MAX = (int)127L;
    /**
     * {@snippet lang=c :
     * #define INT8_MAX 127
     * }
     */
    public static int INT8_MAX() {
        return INT8_MAX;
    }
    private static final int INT8_MIN = (int)-128L;
    /**
     * {@snippet lang=c :
     * #define INT8_MIN -128
     * }
     */
    public static int INT8_MIN() {
        return INT8_MIN;
    }
    private static final int UINT8_MAX = (int)255L;
    /**
     * {@snippet lang=c :
     * #define UINT8_MAX 255
     * }
     */
    public static int UINT8_MAX() {
        return UINT8_MAX;
    }
    private static final int INT_LEAST8_MIN = (int)-128L;
    /**
     * {@snippet lang=c :
     * #define INT_LEAST8_MIN -128
     * }
     */
    public static int INT_LEAST8_MIN() {
        return INT_LEAST8_MIN;
    }
    private static final int INT_LEAST8_MAX = (int)127L;
    /**
     * {@snippet lang=c :
     * #define INT_LEAST8_MAX 127
     * }
     */
    public static int INT_LEAST8_MAX() {
        return INT_LEAST8_MAX;
    }
    private static final int UINT_LEAST8_MAX = (int)255L;
    /**
     * {@snippet lang=c :
     * #define UINT_LEAST8_MAX 255
     * }
     */
    public static int UINT_LEAST8_MAX() {
        return UINT_LEAST8_MAX;
    }
    private static final int INT_FAST8_MIN = (int)-128L;
    /**
     * {@snippet lang=c :
     * #define INT_FAST8_MIN -128
     * }
     */
    public static int INT_FAST8_MIN() {
        return INT_FAST8_MIN;
    }
    private static final int INT_FAST8_MAX = (int)127L;
    /**
     * {@snippet lang=c :
     * #define INT_FAST8_MAX 127
     * }
     */
    public static int INT_FAST8_MAX() {
        return INT_FAST8_MAX;
    }
    private static final int UINT_FAST8_MAX = (int)255L;
    /**
     * {@snippet lang=c :
     * #define UINT_FAST8_MAX 255
     * }
     */
    public static int UINT_FAST8_MAX() {
        return UINT_FAST8_MAX;
    }
    private static final long INTPTR_MIN = -9223372036854775808L;
    /**
     * {@snippet lang=c :
     * #define INTPTR_MIN -9223372036854775808
     * }
     */
    public static long INTPTR_MIN() {
        return INTPTR_MIN;
    }
    private static final long INTPTR_MAX = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define INTPTR_MAX 9223372036854775807
     * }
     */
    public static long INTPTR_MAX() {
        return INTPTR_MAX;
    }
    private static final long UINTPTR_MAX = -1L;
    /**
     * {@snippet lang=c :
     * #define UINTPTR_MAX -1
     * }
     */
    public static long UINTPTR_MAX() {
        return UINTPTR_MAX;
    }
    private static final long PTRDIFF_MIN = -9223372036854775808L;
    /**
     * {@snippet lang=c :
     * #define PTRDIFF_MIN -9223372036854775808
     * }
     */
    public static long PTRDIFF_MIN() {
        return PTRDIFF_MIN;
    }
    private static final long PTRDIFF_MAX = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define PTRDIFF_MAX 9223372036854775807
     * }
     */
    public static long PTRDIFF_MAX() {
        return PTRDIFF_MAX;
    }
    private static final long SIZE_MAX = -1L;
    /**
     * {@snippet lang=c :
     * #define SIZE_MAX -1
     * }
     */
    public static long SIZE_MAX() {
        return SIZE_MAX;
    }
    private static final long INTMAX_MIN = -9223372036854775808L;
    /**
     * {@snippet lang=c :
     * #define INTMAX_MIN -9223372036854775808
     * }
     */
    public static long INTMAX_MIN() {
        return INTMAX_MIN;
    }
    private static final long INTMAX_MAX = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define INTMAX_MAX 9223372036854775807
     * }
     */
    public static long INTMAX_MAX() {
        return INTMAX_MAX;
    }
    private static final long UINTMAX_MAX = -1L;
    /**
     * {@snippet lang=c :
     * #define UINTMAX_MAX -1
     * }
     */
    public static long UINTMAX_MAX() {
        return UINTMAX_MAX;
    }
    private static final int SIG_ATOMIC_MIN = (int)-2147483648L;
    /**
     * {@snippet lang=c :
     * #define SIG_ATOMIC_MIN -2147483648
     * }
     */
    public static int SIG_ATOMIC_MIN() {
        return SIG_ATOMIC_MIN;
    }
    private static final int SIG_ATOMIC_MAX = (int)2147483647L;
    /**
     * {@snippet lang=c :
     * #define SIG_ATOMIC_MAX 2147483647
     * }
     */
    public static int SIG_ATOMIC_MAX() {
        return SIG_ATOMIC_MAX;
    }
    private static final int WINT_MIN = (int)0L;
    /**
     * {@snippet lang=c :
     * #define WINT_MIN 0
     * }
     */
    public static int WINT_MIN() {
        return WINT_MIN;
    }
    private static final int WINT_MAX = (int)65535L;
    /**
     * {@snippet lang=c :
     * #define WINT_MAX 65535
     * }
     */
    public static int WINT_MAX() {
        return WINT_MAX;
    }
    private static final int WCHAR_MAX = (int)65535L;
    /**
     * {@snippet lang=c :
     * #define WCHAR_MAX 65535
     * }
     */
    public static int WCHAR_MAX() {
        return WCHAR_MAX;
    }
    private static final int WCHAR_MIN = (int)0L;
    /**
     * {@snippet lang=c :
     * #define WCHAR_MIN 0
     * }
     */
    public static int WCHAR_MIN() {
        return WCHAR_MIN;
    }
    /**
     * {@snippet lang=c :
     * #define PG_MAJORVERSION "14"
     * }
     */
    public static MemorySegment PG_MAJORVERSION() {
        class Holder {
            static final MemorySegment PG_MAJORVERSION
                = pg_query_h.LIBRARY_ARENA.allocateFrom("14");
        }
        return Holder.PG_MAJORVERSION;
    }
    /**
     * {@snippet lang=c :
     * #define PG_VERSION "14.6"
     * }
     */
    public static MemorySegment PG_VERSION() {
        class Holder {
            static final MemorySegment PG_VERSION
                = pg_query_h.LIBRARY_ARENA.allocateFrom("14.6");
        }
        return Holder.PG_VERSION;
    }
}

